stomatology/home/urls.py
from django.urls import path
from . import views
from .views import NewsList


urlpatterns = [
    path("", NewsList.as_view(), name="home"),
    path("about", views.about, name="about"),
]

stomatology/medical_appointments/urls.py
from django.urls import path, include
from .views import (
    CreateAppointment,
    ListMyAppointments,
    ListDoctorAppointments,
    AjaxHandlerView,
    doctor_update_appointment,
)
from medical_appointments.decorators import doctor_only
from users.decorators import chip_number_needed


urlpatterns = [
    path(
        "create",
        chip_number_needed(CreateAppointment.as_view()),
        name="appointment",
    ),
    path(
        "my_appointments",
        ListMyAppointments.as_view(),
        name="my_appointments",
    ),
    path(
        "doctor_appointments",
        doctor_only(ListDoctorAppointments.as_view()),
        name="doctor_appointments",
    ),
    path(
        "doctor_appointments/<int:appointment_id>/",
        doctor_update_appointment,
        name="doctor_appointment_update",
    ),
    path("doctor_form_change_ajax", AjaxHandlerView.as_view(), name="ajax_appointment"),
]

stomatology/stomatology/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.decorators import unauthenticated_user, chip_number_needed
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.register, name="register"),
    path("", include("home.urls")),
    path(
        "login/",
        unauthenticated_user(
            auth_views.LoginView.as_view(template_name="users/login.html")
        ),
        name="login",
    ),
    path(
        "logout/",
        login_required(
            auth_views.LogoutView.as_view(template_name="users/logout.html")
        ),
        name="logout",
    ),
    path("profile/", user_views.profile, name="profile"),
    path("profile/update", user_views.update_profile, name="update_profile"),
    path("appointments/", include("medical_appointments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stomatology/medical_appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from users.models import Doctor


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    appointment_date = models.DateTimeField()
    doctor = models.ForeignKey(Doctor, on_delete=models.PROTECT)
    comment = models.TextField(blank=True, max_length=500)
    is_closed = models.BooleanField(default=False)
    is_visited = models.BooleanField(default=False)
    doctor_comment = models.TextField(blank=True, max_length=500)
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Запись {self.user.last_name} {self.user.first_name} к {self.doctor} на {self.appointment_date}"

    def get_absolute_url(self):
        return reverse("appointment", kwargs={"pk": self.pk})


class WorkingSchedule(models.Model):
    appointment_time = models.DateTimeField()
    is_available = models.BooleanField(default=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.appointment_time}"

stomatology/medical_appointments/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import Appointment, WorkingSchedule


class StomatologyAppointmentForm(forms.ModelForm):
    queryset = None
    appointment_date = forms.ModelChoiceField(queryset=queryset)

    class Meta:
        model = Appointment
        exclude = ["user", "is_closed", "is_visited", "doctor_comment", "creation_time"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["appointment_date"].queryset = WorkingSchedule.objects.none()
        if "doctor" in self.data:
            try:
                doctor_id = int(self.data.get("doctor"))
                print(
                    WorkingSchedule.objects.filter(
                        doctor=doctor_id, is_available=True
                    ).order_by("appointment_time")
                )
                self.fields[
                    "appointment_date"
                ].queryset = WorkingSchedule.objects.filter(
                    doctor=doctor_id, is_available=True
                ).order_by(
                    "appointment_time"
                )
            except (ValueError, TypeError):
                pass


class StomatologyAppointmentFormDoctor(forms.ModelForm):
    class Meta:
        model = Appointment
        exclude = ["doctor", "user", "appointment_date", "comment", "creation_time"]

stomatology/medical_appointments/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import (
    StomatologyAppointmentForm,
    StomatologyAppointmentFormDoctor,
)
from django.views.generic import CreateView, ListView, View
from .models import Appointment, WorkingSchedule
from users.models import Doctor
from .decorators import doctor_only


class CreateAppointment(LoginRequiredMixin, CreateView):
    form_class = StomatologyAppointmentForm
    template_name = "medical_appointments/appointment.html"
    success_url = reverse_lazy("profile")
    redirect_field_name = "login"

    def form_valid(self, form):
        appointment_form = form.save(commit=False)
        appointment_form.user = self.request.user
        appointment_form.save()
        super().form_valid(form)

        return HttpResponseRedirect(self.get_success_url())


class ListMyAppointments(LoginRequiredMixin, ListView):
    model = Appointment

    def get_queryset(self):
        return Appointment.objects.filter(user_id=self.request.user.id)


class ListDoctorAppointments(LoginRequiredMixin, ListView):
    model = Appointment
    template_name = "medical_appointments/doctor_appointments.html"

    def get_queryset(self):
        return Appointment.objects.filter(
            doctor_id=Doctor.objects.filter(user_id=self.request.user.id)[0],
            is_closed=False,
        )


@doctor_only
def doctor_update_appointment(request, appointment_id):
    appointment_item = get_object_or_404(Appointment, id=appointment_id)
    if (
        appointment_item.doctor_id
        != Doctor.objects.filter(user_id=request.user.id).first().id
    ):
        messages.warning(request, "Вы не являетесь ведущим врачом для этой формы")
        return redirect("doctor_appointments")

    if appointment_item.is_closed == True:
        messages.warning(
            request,
            "Данная форма уже закрыта и вы не имеете права получить к ней доступ",
        )
        return redirect("doctor_appointments")

    if request.method == "POST":
        form = StomatologyAppointmentFormDoctor(request.POST, instance=appointment_item)
        if form.is_valid():
            form.save()
            messages.success(request, f"Вы завершили прием!")

            return redirect("doctor_appointments")

    form = StomatologyAppointmentFormDoctor(instance=appointment_item)
    context = {"form": form}
    return render(
        request, "medical_appointments/doctor_update_appointment.html", context
    )


class AjaxHandlerView(View):
    def get(self, request):
        doctor_id = request.GET.get("doctor_id")
        dates = WorkingSchedule.objects.filter(
            doctor=doctor_id, is_available=True
        ).all()
        return render(
            request,
            "medical_appointments/dates_dropdown_list_options.html",
            {"dates": dates},
        )

stomatology/medical_appointments/templates/medical_appointments/appointment.html
{% extends 'home/base.html'%}
{% load crispy_forms_tags %}

{% block title %}
Запись на прием
{% endblock %}


{% block content %}

<h1>Записаться на прием</h1>
    <form method="post" id="appointmentForm" data-time-url={%url "ajax_appointment"%}>
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"></legend>
            {{form | crispy}}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Записаться</button>
        </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_doctor").change(function () {
        const url = $("#appointmentForm").attr("data-time-url");
        const doctorId = $(this).val();  

        $.ajax({                      
            url: url,                  
            data: {
                'doctor_id': doctorId 
            },
            success: function (response) { 
                $("#id_appointment_date").html(response);
            }
        });

    });
</script>
{% endblock %}

stomatology/medical_appointments/templates/medical_appointments/appointment_list.html
{% extends 'home/base.html'%}
{% block title %}
Мои записи
{% endblock %}

{% block content %}
{% for item in object_list %}
<div class="card mb-3">
    <div class="card-body">
        <div class="media">
            <div class="media-body">
                <h5 class="card-title">{{item}}</h5>
                <p class="card-text">{{ item.comment|safe|linebreaks|truncatewords:50 }}</p>
            </div>
        </div>

    </div>
</div>
{% endfor %}
    
{% endblock %}

stomatology/medical_appointments/templates/medical_appointments/dates_dropdown_list_options.html
<option value="">          </option>
{% for date in dates %}
<option value="{{ date.id }}">{{ date.appointment_time }}</option>
{% endfor %}

stomatology/medical_appointments/templates/medical_appointments/doctor_appointments.html
{% extends 'home/base.html'%}
{% block title %}
Записи к вам
{% endblock %}

{% block content %}
{% for item in object_list %}
<div class="card mb-3">
    <div class="card-body">
        <div class="media">
            <div class="media-body">
                <h5 class="card-title">{{item}}</h5>
                <p class="card-text">{{ item.comment|safe|linebreaks|truncatewords:50 }}</p>
                <div class="form-group">
                    <a href="{%url "doctor_appointment_update" item.id%}">Обработать</a> 
                </div>
            </div>
        </div>

    </div>
</div>
{% endfor %}
    
{% endblock %}

stomatology/medical_appointments/templates/medical_appointments/doctor_update_appointment.html
{% extends 'home/base.html'%}
{% load crispy_forms_tags %}
{% block title %}
Обработка приёма
{% endblock %}


{% block content %}
<h1>Обработка приёма</h1>
    <form method="post" action="">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"></legend>
            {{form | crispy}}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Обработать</button>
        </div>
    </form>
{% endblock %}